#DUBBOX
dubbox:
  application: 
    name: xbin-store-service-shiro
    organization: dubbox
    owner: hl
  registry: 
    protocol: zookeeper
    address: 127.0.0.1:2181
  annotation:
    package: cn.binux.shiro
  protocol:
    name: dubbo
    port: 20899
    #host: 192.168.125.1
    timeout: 30000
    threadpool: fixed
    threads: 500
    accepts: 1000
    serialization: kryo
    optimizer: cn.binux.serial.SerializationOptimizerImpl
  monitor:
    enabled: false
    address: 192.168.125.1:6060
    username: admin
    password: admin

druid:
    url: jdbc:mysql://localhost:3306/gyl?characterEncoding=utf-8
    driver-class: com.mysql.jdbc.Driver
    username: root
    password: root
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-While-Idle: true
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j,config
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=false
    monitor:
          enabled: false #如果需要打开监控需要enabled,xbin-store-common-mapper中加入spring boot web
          druid-stat-view: /druid/*
          druid-web-stat-filter: /*
          allow: 219.230.50.107,127.0.0.1
          deny: 192.168.1.73
          login-username: admin
          login-password: 123456
          exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
          reset-enable: false
mybatis:
    type-aliases-package: cn.binux.pojo.sys
    mapper-locations: classpath:mapper/sys/*.xml


pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
server:
  port: 8888
  context-path: /hl
  

  